extends:
  - 'airbnb-base/legacy'

env:
  browser: false
  node: true

globals:
  describe: true
  it: true

rules:
  indent: [2, 4, { SwitchCase: 1, VariableDeclarator: 1 }]
  brace-style: [2, 'stroustrup', { allowSingleLine: true }]
  space-before-function-paren: [2, { anonymous: 'never', named: 'never' }]
  new-cap: [2, { newIsCap: true }]
  func-names: 0
  consistent-return: 0
  global-require: 0
  wrap-iife: [2, 'inside']
  import/no-unresolved: [2, { commonjs: true }]

  # Remove this later maybe
  no-useless-escape: 0
  no-underscore-dangle: 0
  no-restricted-syntax: [2, 'DebuggerStatement', 'LabeledStatement', 'WithStatement']
  newline-per-chained-call: 0
  no-param-reassign: 0
  comma-dangle: [2, 'never']
  vars-on-top: 0
  max-len: [1, 200, 2, { ignoreUrls: true, ignoreComments: false }]
